# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: "10:00"
  commit-message:
    prefix: ci
    prefix-development: ci
    include: scope
  labels:
  - dependencies
  - gha
  - pinned

- package-ecosystem: maven
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: "10:00"
  commit-message:
    prefix: fix
    prefix-development: build
    include: scope
  labels:
  - dependencies
  - mvn
  - pinned
  ignore:
  - dependency-name: "com.vegardit.maven.no-npe:*"
