# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches-ignore:  # build all branches except:
    - "dependabot/**"  # prevent GHA triggered twice (once for commit to the branch and once for opening/syncing the PR)
    tags-ignore:  # don't build tags
    - "**"
    paths-ignore:
    - ".act*"
    - "**/*.adoc"
    - "**/*.md"
    - ".editorconfig"
    - ".git*"
    - ".github/*.yml"
    - ".github/ISSUE_TEMPLATE/*"
    - ".github/workflows/stale.yml"
    - "codecov.yml"
  pull_request:
    paths-ignore:
    - ".act*"
    - "**/*.adoc"
    - "**/*.md"
    - ".editorconfig"
    - ".git*"
    - ".github/*.yml"
    - ".github/ISSUE_TEMPLATE/*"
    - ".github/workflows/stale.yml"
    - "codecov.yml"
  repository_dispatch:
    types: [new-haxe4e-release]
  workflow_dispatch:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch
    inputs:
      extra-maven-args:
        description: "Additional command-line arguments to append to all Maven invocations"
        required: false
        type: string
      debug-with-ssh:
        description: "Start an SSH session for debugging purposes at the end of the build:"
        default: never
        type: choice
        options: [ always, on_failure, on_failure_or_cancelled, never ]
      debug-with-ssh-only-for-actor:
        description: "Restrict SSH debug session access to the GitHub user who triggered the workflow"
        default: true
        type: boolean

jobs:
  ###########################################################
  eclipse-product-build:
  ###########################################################
    uses: sebthom/gha-shared/.github/workflows/reusable.eclipse-product-build.yml@v1
    with:
      timeout-minutes: 30

      product-files: product/haxe-studio.product
      target-files: build.target
  
      extra-maven-args: ${{ inputs.extra-maven-args }}
  
      development-branch: main
      development-updatesite-branch: updatesite-preview
      release-branch: release
      release-updatesite-branch: updatesite

      debug-with-ssh: ${{ inputs.debug-with-ssh || 'never' }}
      debug-with-ssh-only-for-actor: ${{ inputs.debug-with-ssh-only-for-actor || true }}

    permissions:
      actions: write       # to delete action cache entries
      contents: write      # to create releases (commit to updatesite branches)
      pull-requests: write # for dependabot auto merges
